export default {
  architecture: 'Architecture',
  'proposal-lifecycle': 'Proposal lifecycle',
  'connect-a-repo': 'Connect a repo',
  'platform-repo-layout': 'Platform repo layout',
  'environment-profile': 'Environment profile',
  'maturity-scoring': 'Maturity scoring',
  constitution: 'Constitution',
  'policy-in-force': 'Policy in force',
  'rule-naming-standard': 'Rule-naming standard',
  'knowledge-packs': 'Knowledge packs',
  'specialist-packs': 'Specialist Packs',
  'runner-helm-chart': 'Runner Helm chart',
  'llm-provider': 'LLM provider (BYO key)',
  'runner-cli': 'Runner CLI',
  'policy-linter': 'Policy linter',
  'mcp-server': 'Integration model',
  'supply-chain': 'Supply-chain verification',
  versioning: 'Versioning and releases',
  license: 'License'
}
